project:
  type: website
  output-dir: _site
website:
  open-graph: true
  twitter-card: true
  site-url: https://tbep-tech.github.io/ccmp
  repo-url: https://github.com/tbep-tech/ccmp
  # issue-url: https://github.com/tbep-tech/ccmp/issues
  # repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: false
  search: true
  page-footer:
    left: |
      &copy; [Tampa Bay Estuary Program](https://tbep.org). All Rights Reserved. [Contact](https://tbep.org/about-tbep/contact/) | [Accountability Act](https://tbep.org/uniform-special-district-accountability-act/) | [Privacy](https://tbep.org/privacy-policy/) | [Site Credit](https://tangram3ds.com/)
    right:
      - icon: github
        href: https://github.com/tbep-tech/ccmp
        aria-label: Quarto GitHub
  navbar:
    background: light
    collapse-below: lg
    title: "{{< meta params.navtitle >}}"
    left:
      - text: "Water"
        href: docs/water/wq1.qmd
      - text: "Wildlife"
        href: docs/wildlife/bh1.qmd
      - text: "Community"
        href: docs/communities/pe1.qmd
  sidebar:
  
    - id: clean-water-and-sediments
      title: "Clean Water and Sediments"
      collapse-level: 1
      contents:
        - section: "Action"
        - '---'
        - section: "Water Quality"
          contents:
            - text: "WQ-1"
              href: docs/water/wq1.qmd
            - text: "WQ-3"
              href: docs/water/wq3.qmd
        - section: "Stormwater Runoff"
          contents:
            - text: "SW-1" 
              href: docs/water/sw1.qmd
            - text: "SW-8"
              href: docs/water/sw8.qmd
            - text: "SW-10"
              href: docs/water/sw10.qmd
        - section: "Atmospheric Deposition"
          contents:
            - text: "AD-1"
              href: docs/water/ad1.qmd
        - section: "Wastewater Discharge"
          contents:
            - text: "WW-1"
              href: docs/water/ww1.qmd
            - text: "WW-2"
              href: docs/water/ww2.qmd
            - text: "WW-3"  
              href: docs/water/ww3.qmd
            - text: "WW-5"
              href: docs/water/ww5.qmd
        - section: "Contaminants of Concern"
          contents:
            - text: "COC-1"
              href: docs/water/coc1.qmd
            - text: "COC-4"
              href: docs/water/coc4.qmd
        - section: "Pathogens"
          contents:
            - text: "PH-2"
              href: docs/water/ph2.qmd
            - text: "PH-4"
              href: docs/water/ph4.qmd
            - text: "PH-5"
              href: docs/water/ph5.qmd
            
    - id: thriving-habitats-and-abundant-widlife
      title: "Thriving Habitats and Abundant Wildlife"
      collapse-level: 1
      contents:
        - section: "Action"
        - '---'
        - section: "Bay Habitats"
          contents:
            - text: "BH-1"
              href: docs/wildlife/bh1.qmd
            - text: "BH-2"
              href: docs/wildlife/bh2.qmd
            - text: "BH-3"
              href: docs/wildlife/bh3.qmd
            - text: "BH-4"
              href: docs/wildlife/bh4.qmd
            - text: "BH-6"
              href: docs/wildlife/bh6.qmd
            - text: "BH-8"
              href: docs/wildlife/bh8.qmd
            - text: "BH-9"
              href: docs/wildlife/bh9.qmd
        - section: "Freshwater Inflow"
          contents: 
            - text: "FI-1"
              href: docs/wildlife/fi1.qmd
        - section: "Fish & Wildlife"
          contents:
            - text: "FW-1" 
              href: docs/wildlife/fw1.qmd
            - text: "FW-3"
              href: docs/wildlife/fw3.qmd
            - text: "FW-5"
              href: docs/wildlife/fw5.qmd
            - text: "FW-6"
              href: docs/wildlife/fw6.qmd
        - section: "Dredging & Material Management"
          contents:
            - text: "DR-1"
              href: docs/wildlife/dr1.qmd
            - text: "DR-2"
              href: docs/wildlife/dr2.qmd
        - section: "Spill Prevention"
          contents:
            - text: "SP-1"
              href: docs/wildlife/sp1.qmd
            - text: "SP-2"
              href: docs/wildlife/sp2.qmd
        - section: "Invasive Species"
          contents:
            - text: "IS-2"
              href: docs/wildlife/is2.qmd
              
    - id: informed-engaged-and-responsible-community
      title: "Informed, Engaged, and Responsible Community"
      collapse-level: 1
      contents:
        - section: "Action"
        - '---'
        - section: "Public Education"
          contents:
            - text: "PE-1"
              href: docs/communities/pe1.qmd
            - text: "PE-2"
              href: docs/communities/pe2.qmd
        - section: "Public Access"
          contents:
            - text: "PA-1" 
              href: docs/communities/pa1.qmd
        - section: "Climate Change"
          contents:
            - text: "CC-1"
              href: docs/communities/cc1.qmd
            - text: "CC-2"
              href: docs/communities/cc2.qmd
        - section: "Local Implementation"
          contents: 
            - text: "LI-1"
              href: docs/communities/li1.qmd
      
    - id: acronyms
      contents: 
        section: " "
        href: docs/misc/acronyms.qmd
        
    - id: priorities
      contents: 
        section: " "
        href: docs/misc/priorities.qmd
        
    - id: implement
      contents: 
        section: " "
        href: docs/misc/implement.qmd
        
    - id: all-actions
      contents: 
        section: " "
        href: docs/misc/allactions.qmd
        
bibliography: docs/refs.bib
# suppress-bibliography: true
citeproc: true
link-citations: true
citations-hover: false
citation-location: margin

format:
  html:
    anchor-sections: false
    include-before-body:
      text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    include-after-body:
      text: |
        <script type="application/javascript">
          function readMore() {
            var moreText = document.getElementById("more");
            var introText = document.getElementById("intro");            
            var btnText = document.getElementById("readMore");
            if (moreText.style.display === "none") {
              btnText.innerHTML = "Read more";
              moreText.style.display = "none";
            } else {
              btnText.style.display = "none";
              introText.style.maskImage = "none";
              moreText.style.display = "grid";
            }
          }
        </script>    
    toc: true
    theme:
      light: [cosmo]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
execute:
  echo: false
  message: false
  warning: false

editor: source