project:
  type: website
  output-dir: _site

website:
  image: "tarponlogo.png"
  open-graph: true
  twitter-card: true
  site-url: https://tbep-tech.github.io/ccmp
  repo-url: https://github.com/tbep-tech/ccmp
  issue-url: https://github.com/tbep-tech/ccmp/issues
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  search:
    show-item-context: true
    type: overlay
  # body-footer: docs/footer.qmd
  page-footer:
    left: |
      &copy; [Tampa Bay Estuary Program](https://tbep.org)
    center:
      - text: "Contact Us"
        href: https://tbep.org
    right:
      - icon: github
        href: https://github.com/tbep-tech
        aria-label: Quarto GitHub
  navbar:
    background: light
    logo: tarponlogo.png
    logo-alt: "TBEP tarpon logo"
    title: false
    collapse-below: lg
    left:
      - text: "Clean Water and Sediments"
        href: docs/clean-water-and-sediments/wq1.qmd
      - text: "Thriving Habitats and Abundant Wildlife"
        href: docs/wildlife/bh1.qmd
      - text: "Informed, Engaged, and Responsible Communities"
        href: docs/communities/pe1.qmd
    tools:
      - icon: github
        href: https://github.com/tbep-tech/ccmp
        text: TBEP GitHub

  sidebar:
    - id: clean-water-and-sediments
      title: "Clean Water and Sediments"
      contents:
        - section: "Action"
        - '---'
        - section: "Water Quality"
          contents:
            - text: "WQ-1"
              href: docs/clean-water-and-sediments/wq1.qmd
            - text: "WQ-2"
              href: docs/clean-water-and-sediments/wq2.qmd
        - section: "Stormwater"
          contents:
            - text: "SW-1" 
              href: docs/clean-water-and-sediments/sw1.qmd
            - text: "SW-2"
              href: docs/clean-water-and-sediments/sw2.qmd
    
    - id: thriving-habitats-and-abundant-widlife
      title: "Thriving Habitats and Abundant Wildlife"
      contents:
        - section: "Action"
        - '---'
        - section: "Bay Habitats"
          contents:
            - text: "BH-1"
              href: docs/wildlife/bh1.qmd
            - text: "BH-2"
              href: docs/wildlife/bh2.qmd
        - section: "Fish and Wildlife"
          contents:
            - text: "FW-1" 
              href: docs/wildlife/fw1.qmd
            - text: "FW-2"
              href: docs/wildlife/fw2.qmd
              
    - id: informed-engaged-and-responsible-community
      title: "Informed, Engaged, and Responsible Community"
      contents:
        - section: "Action"
        - '---'
        - section: "Public Education"
          contents:
            - text: "PE-1"
              href: docs/communities/pe1.qmd
            - text: "PE-2"
              href: docs/communities/pe2.qmd
        - section: "Public Access"
          contents:
            - text: "PA-1" 
              href: docs/communities/pa1.qmd
            - text: "PA-2"
              href: docs/communities/pa2.qmd
              
# bibliography: refs.bib

format:
  html:
    toc: true
    theme:
      light: [cosmo]
    code-copy: true
    code-overflow: wrap
    css: stylesworking.css
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px


# filters:
#   - filters/tools-tabset.lua


freeze: true

editor: visual
