---
params:
  navtitle: Implementing and Financing the Plan
toc: false
---

###

This chapter describes how Charting The Course: The Comprehensive Conservation and Management Plan for Tampa Bay will be implemented by local governments, agencies and other bay stakeholders, and discusses financing mechanisms to ensure that the goals of the Plan are achieved.

### THE INTERLOCAL AGREEMENT

In 1998, local government and regulatory partners of the Tampa Bay Estuary Program formally affirmed their commitment to implementing the goals of Charting The Course through the adoption of a precedent-setting Interlocal Agreement.

The agreement, the first of its kind among the nation’s 28 NEPs, represented a binding pledge by TBEP’s major partners to work together to achieve bay recovery targets. The 1998 Interlocal Agreement also established the Tampa Bay Estuary Program as an Independent Special District under Florida Statutes; spelled out the governance structure of the program; and established funding contributions by the signatories based on population.

The Interlocal Agreement was revised and restated in 2021. A key component of the update included a revised funding schedule and dues of our local government partners based on current population estimates. The changes in funding are listed elsewhere in this section.

OTHER HIGHLIGHTS OF THE 2021 AGREEMENT INCLUDE:

-   Participation by local governments, regulatory agencies and other organizations with a stake in the bay’s health. The seven largest local governments in the Tampa Bay region — the counties of Hillsborough, Pinellas, Manatee and Pasco and the cities of Tampa, St. Petersburg and Clearwater — are parties to the agreement, along with the Southwest Florida Water Management District, and the Florida Department of Environmental Protection. The Tampa Port Authority, Environmental Protection Commission of Hillsborough County, Florida Fish and Wildlife Conservation Commission’s Fish and Wildlife Research Institute, Tampa Bay Water, Tampa Bay Regional Planning Council and Manatee County Port Authority are also signatories. A separate agreement signed by Region 4 of the U.S. Environmental Protection Agency during the 2015 update continues and defines EPA’s support for implementing the Plan.
-   The TBEP partners agreed to work together to collectively address CCMP Goals, and adopted measurable and achievable goals to maintain important water quality and seagrass gains.

### FINANCING THE PLAN

TBEP has historically and will continue to pursue at least eight separate avenues to secure funding or in-kind support to finance operation of the base program and to advance implementation of the CCMP. The updated financing plan includes a balance of both dedicated and variable funding sources at federal, state, and local levels as well as private and non-profit sources.

The major objectives of the financing strategy are:

-   Developing dedicated sources of funding to sustain the base operations of the TBEP, including personnel, administrative cost, community outreach, environmental monitoring and technical support.
-   Securing dedicated and variable sources of funding that enhance implementation of the CCMP and maintain adequate progress toward bay restoration goals.

#### Dedicated Funding Sources

Currently, the following four funding sources provide dedicated or reasonably secure funding to support the base program and/or enhance CCMP implementation, over both the short-term and long-term.

-   <span class="boldtxt">Federal NEP Funding.</span> Each action plan in the Revised CCMP indicates whether it will be funded under the Clean Water Act Section 320, versus other funding sources. While the specific future annual appropriations under Section 320 are uncertain, there is strong Congressional support for the community-based conservation efforts of Tampa Bay and the 27 other estuaries that are part of the NEP. In 2021, Congress and the President signed into law the second reauthorization of the National Estuary Program (NEP) since it expired in 2010. The new law authorizes up to \$50 million per year for the National Estuary Program over the next five years. This reauthorization equates to a maximum of about \$1,000,000 per NEP per year through 2026, if annual appropriations equaled the authorized amount.
-   <span class="boldtxt">Funding Commitments in 2021 Interlocal Agreement.</span> The Interlocal Agreement (IA) through which the CCMP is implemented obligates local government and agency partners to fund TBEP costs approved by the Policy Board in the annual program budget. A key component of the 2021 IA update included a revised funding schedule and dues from local partners, adjusted to 2018 US Census Bureau estimates. The revised funding strategy calls for a minimum increase in annual dues of 2.5% per year for 5 years for those member governments contributing to the Tampa Bay Environmental Restoration Fund, and slightly higher annual dues for those members that do not contribute to TBERF. This funding commitment will allow TBEP to keep up with inflation and continue to provide support to our partners. When coupled with the anticipated federal NEP allocation administered through EPA and other external grants, local government and agency cash contributions are expected to meet the amount required to fully support program operations through 2026.
-   <span class="boldtxt">Specialty License Plate.</span> Revenue from the Tampa Bay Estuary specialty license plate has generated more than \$2.1 million since 2000, the first full year of plate sales. The Policy Board is authorized under the state law that created the Tampa Bay Estuary plate to use those funds for any types of projects that contribute to CCMP implementation. Over the last 10 years, the majority of these funds have been authorized to support TBEP’s successful Bay Mini-Grant Program. Bay Mini-Grants generate tens of thousands of dollars in matching funds and in-kind services. Up to 10% of TBEP’s annual portion of the Tampa Bay Estuary tag revenues can be used for administration of the grant program (typically about \$8,000 available per year).
-   <span class="boldtxt">Tampa Bay Environmental Restoration Fund.</span> TBERF is a partnership of Tampa Bay Estuary Program, Restore America’s Estuaries, local governments, and private industry. TBERF was created to raise funds for projects that help advance implementation of the CCMP. To date, TBERF awarded more than \$8.5 million in grants for projects throughout the bay area that contribute to CCMP implementation. These projects leveraged an additional \$14 million in project implementation costs. TBEP staff are actively exploring opportunities to increase contributions from public and private entities in the Tampa Bay region, and recent Clean Water Act settlement agreements have directed funds to the program. TBERF administrative fees have generated about \$50,000 per year since 2014.

#### Variable Funding Sources

The following funding sources supplement CCMP implementation through local action plans of TBEP partners, grants, cooperative agreements and other mechanisms. While variable from year to year, they represent significant funding sources to support both short- and long-term resource needs as identified in the CCMP Actions for TBEP and its partners.

-   <span class="boldtxt">External Grants and Cooperative Agreements.</span> TBEP staff have had significant success partnering with federal, state and local agencies to secure hundreds of thousands of dollars in grants for developing management tools and for research, environmental monitoring, habitat restoration, water quality improvement and environmental education projects as called for in the CCMP. Funding sources for these external grants include Bipartisan Infrastructure Law (BIL), NASA, NSF, FDOT, USFWS, NOAA, EPA and SWFWMD. TBEP will continue to pursue these opportunities as a means of financing priority research, monitoring, and resource management needs.
-   <span class="boldtxt">RESTORE funds from Deepwater Horizon oil spill fines and penalties.</span> TBEP secured approximately \$1.5 million from the 2015 Funded Priorities List and another \$9.5 million from the 2021 Funded Priorities List (3b). Several of our local partners have also submitted projects for other RESTORE funds that meet our CCMP objectives.
-   <span class="boldtxt">Non-Federal Overmatch Fund.</span> TBEP maintains a Non-Federal Overmatch Fund that provides a source of matching funds for federal grants helping to implement the CCMP and serves as a contingency fund for continuing program operations in the event a major funding source is lost. Expenses which cannot be paid for with federal money such as the program’s dues to the Association of National Estuary Programs are also funded from the Overmatch Fund. The fund balance as of October 2023 was about \$340,000.
-   <span class="boldtxt">Philanthropic Donations.</span> The Program has received increasing private donations through 2023. Total annual donations increased from \$21,539 in 2018 to \$42,640 in 2023. Depending upon the donation stipulations, these funds are directed towards unrestricted program operations, the Bay Mini-Grant or TBERF programs to help implement the CCMP. The fund balance as of October 2023 was about \$83,000.

<span class="blank">@empty</span>

{{< include ../footer.qmd >}}
