---
params:
  navtitle: Acronyms
toc: false
---

<span class="acronym">__ABM__</span>Agency on Bay Management \
<span class="acronym">__ACP__</span>Area Contingency Plan \
<span class="acronym">__AIS__</span>Automatic Identification System \
<span class="acronym">__ASR__</span>Aquifer Storage and Recovery \
<span class="acronym">__ATON__</span>Aids To Navigation \
<span class="acronym">__AWT__</span>Advanced Wastewater Treatment \
<span class="acronym">__BASIS__</span>Bay Area Science and Information Symposium \
<span class="acronym">__BPA__</span>Bisphenol A \
<span class="acronym">__BMAP__</span>Basin Management Action Plan \
<span class="acronym">__BMP__</span>Best Management Practice \
<span class="acronym">__BOD__</span>Biochemical Oxygen Demand \
<span class="acronym">__BRACE__</span>Bay Region Atmospheric Chemistry Experiment \
<span class="acronym">__CAC__</span>Community Advisory Committee (TBEP) \
<span class="acronym">__CAFE__</span>Corporate Average Fuel Economy \
<span class="acronym">__CAFO__</span>Concentrated Animal Feeding Operation \
<span class="acronym">__CARES__</span>County Alliance for Responsible Environmental Stewardship \
<span class="acronym">__CCHA__</span>Critical Coastal Habitat Assessment \
<span class="acronym">__CCMP__</span>Comprehensive Conservation and Management Plan \
<span class="acronym">__CHNEP__</span>Coastal and Heartland National Estuary Partnership \
<span class="acronym">__CISMA__</span>Cooperative Invasive Species Management Area \
<span class="acronym">__COC__</span>Contaminant of Concern \
<span class="acronym">__CRE__</span>Climate Ready Estuaries \
<span class="acronym">__CSAP__</span>Tampa Bay Climate Science Advisory Panel \
<span class="acronym">__CVIS__</span>Cooperative Vessel Tracking Service \
<span class="acronym">__CWA__</span>Clean Water Act \
<span class="acronym">__CWA__</span>Critical Wildlife Area (FWC) \
<span class="acronym">__DMMA__</span>Dredged Material Management Areas \
<span class="acronym">__DMMP__</span>Dredged Material Management Plan \
<span class="acronym">__DMR__</span>Discharge Monitoring Report \
<span class="acronym">__EDC__</span>Endocrine Disrupting Compound \
<span class="acronym">__ELAPP__</span>Environmental Lands Acquisition and Protection Program \
<span class="acronym">__EPA__</span>United States Environmental Protection Agency \
<span class="acronym">__EPCHC__</span>Environmental Protection Commission of Hillsborough County \
<span class="acronym">__ERP__</span>Environmental Resource Permit \
<span class="acronym">__EzDMR__</span>Electronic Discharge Monitoring Reporting system \
<span class="acronym">__FAC__</span>Florida Administrative Code \
<span class="acronym">__FARMS__</span>Facilitating Agricultural Resource Management System \
<span class="acronym">__FDACS__</span>Florida Department of Agriculture and Consumer Services \
<span class="acronym">__FDEP__</span>Florida Department of Environmental Protection \
<span class="acronym">__FDOH__</span>Florida Department of Health \
<span class="acronym">__FDOT__</span>Florida Department of Transportation \
<span class="acronym">__FIM__</span>Fisheries Independent Monitoring Program \
<span class="acronym">__FIO__</span>Florida Institute of Oceanography \
<span class="acronym">__FNMP__</span>Florida Master Naturalist Program \
<span class="acronym">__FOG__</span>Fats, Oils and Grease \
<span class="acronym">__FPL__</span>Florida Power and Light \
<span class="acronym">__FWC__</span>Florida Fish and Wildlife Conservation Commission  \
<span class="acronym">__FWRI__</span>Fish and Wildlife Research Institute \
<span class="acronym">__FY&N__</span>Florida Yards and Neighborhoods \
<span class="acronym">__GCOOS__</span>Gulf of Mexico Coastal Ocean Observing System \
<span class="acronym">__GIS__</span>Geographic Information System         \
<span class="acronym">__GOMA__</span>Gulf of Mexico Alliance \
<span class="acronym">__GPRA__</span>Government Performance and Results Act \
<span class="acronym">__HAB__</span>Harmful Algal Bloom \
<span class="acronym">__HBMP__</span>Hydro-Biological Monitoring Program \
<span class="acronym">__IRL__</span>Indian River Lagoon         \
<span class="acronym">__ISMP__</span>Imperiled Species Management Plan \
<span class="acronym">__KTTB__</span>Keep Tampa Bay Beautiful \
<span class="acronym">__LEPC__</span>Local Emergency Planning Committee \
<span class="acronym">__LID__</span>Low Impact Development \
<span class="acronym">__MAC__</span>Manatee Awareness Committee \
<span class="acronym">__MFL__</span>Minimum Flows and Levels \
<span class="acronym">__MGD__</span>Million Gallons Per Day \
<span class="acronym">__MPO__</span>Metropolitan Planning Organization \
<span class="acronym">__NFWF__</span>National Fish and Wildlife Foundation \
<span class="acronym">__NGO__</span>Non-Governmental Organization \
<span class="acronym">__NIH__</span>National Institutes of Health \
<span class="acronym">__NMFS__</span>National Marine Fisheries Service \
<span class="acronym">__NSF__</span>National Science Foundation \
<span class="acronym">__NOAA__</span>National Oceanic and Atmospheric Administration \
<span class="acronym">__NOx__</span>Nitrogen Oxide \
<span class="acronym">__NPDES__</span>National Pollutant Discharge Elimination System \
<span class="acronym">__OA__</span>Ocean Acidification \
<span class="acronym">__OAWP__</span>Office of Agricultural Water Policy \
<span class="acronym">__PAH__</span>Polycyclic Aromatic Hydrocarbon \
<span class="acronym">__PBDE__</span>Polybrominated Diphenyl Ether \
<span class="acronym">__PCB__</span>Polychlorinated Biphenols \
<span class="acronym">__PFAS__</span>Per- and polyfluoroalkyl substances \
<span class="acronym">__PORTS__</span>Physical Oceanographic Real-Time System \
<span class="acronym">__PPCP__</span>Pharmaceuticals and Personal Care Products \
<span class="acronym">__PRF__</span>Pollution Recovery Fund \
<span class="acronym">__PSA__</span>Public Service Announcement \
<span class="acronym">__PV__</span>Photovoltaic \
<span class="acronym">__RA__</span>Reasonable Assurance document \
<span class="acronym">__REDDy__</span>Introduced Reptile Early Detection and Documentation \
<span class="acronym">__RIB__</span>Rapid Infiltration Basin \
<span class="acronym">__RSM__</span>Regional Sediment Management \
<span class="acronym">__SBEP__</span>Sarasota Bay Estuary Program \
<span class="acronym">__SHARP__</span>South Hillsborough Aquifer Recharge Project \
<span class="acronym">__SLR__</span>Sea Level Rise \
<span class="acronym">__SQAP__</span>Sediment Quality Action Plan \
<span class="acronym">__SSO__</span>Sanitary Sewer Overflow \
<span class="acronym">__SWFWMD__</span>Southwest Florida Water Management District \
<span class="acronym">__SWIM__</span>Surface Water Improvement and Management Plan \
<span class="acronym">__TAC__</span>Technical Advisory Committee (TBEP) \
<span class="acronym">__TAP__</span>Tampa Augmentation Project \
<span class="acronym">__TBARTA__</span>Tampa Bay Area Regional Transit Authority \
<span class="acronym">__TBBI__</span>Tampa Bay Benthic Index \
<span class="acronym">__TBERF__</span>Tampa Bay Environmental Restoration Fund \
<span class="acronym">__TBEP__</span>Tampa Bay Estuary Program \
<span class="acronym">__TBNEP__</span>Tampa Bay National Estuary Program \
<span class="acronym">__TBNMC__</span>Tampa Bay Nitrogen Management Consortium \
<span class="acronym">__TBRPC__</span>Tampa Bay Regional Planning Council  \
<span class="acronym">__TBW__</span>Tampa Bay Watch or Tampa Bay Water \
<span class="acronym">__TECO__</span>Tampa Electric Company \
<span class="acronym">__THSSC__</span>Tampa Bay Harbor Safety and Security Committee \
<span class="acronym">__TMDL__</span>Total Maximum Daily Load \
<span class="acronym">__TN__</span>Total Nitrogen \
<span class="acronym">__TP__</span>Total Phosphorus \
<span class="acronym">__TSS__</span>Total Suspended Solids \
<span class="acronym">__UCF__</span>University of Central Florida \
<span class="acronym">__UF__</span>University of Florida \
<span class="acronym">__UF/IFAS__</span>University of Florida Institute of Food and Agricultural Sciences \
<span class="acronym">__USACE__</span>U.S. Army Corps of Engineers \
<span class="acronym">__USCG__</span>United States Coast Guard \
<span class="acronym">__USF__</span>University of South Florida \
<span class="acronym">__USFWS__</span>United States Fish and Wildlife Service \
<span class="acronym">__USGS__</span>United States Geological Survey \
<span class="acronym">__WWTP__</span>Wastewater Treatment Plant \

{{< include footer.qmd >}}
