on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: build

jobs:
  build-deploy:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          extra-repositories: 'https://tbep-tech.r-universe.dev'
          r-version: '4.3.2'
      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book
          tinytex: true
          # uncomment below and fill to pin a version
          version: 1.4.549
      - name: Setup R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          pak-version: "devel"
          packages: |
            tbeptools
            any::googledrive
            any::googlesheets4
            any::sf
            any::tidyverse
            any::flextable
            any::ggspatial
            any::here
            any::emojifont
            any::scales
            any::htmltools
            any::reactable
            any::rmarkdown
            any::knitr
            any::prettymapr
            any::sysfonts
            any::showtext

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}